name: Publish to PyPI

on:
  push:
    branches:
      - main  # Runs when pushing to main
  release:
    types: [created]  # Runs when creating a GitHub release

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    name: Build and Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest

      - name: Install Project Dependencies from `pyproject.toml`
        run: |
          pip install .

      - name: Run Tests
        run: |
          pytest

      - name: Build Package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --username "$PYPI_USERNAME" --password "$PYPI_PASSWORD" dist/*